# Generated by Django 3.0.7 on 2021-03-13 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Teams',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=250)),
                ('last_name', models.CharField(max_length=250)),
                ('designation', models.CharField(max_length=250)),
                ('photo', models.ImageField(upload_to='photos/%y/%m/%d')),
                ('facebook_link', models.URLField(max_length=100)),
                ('google_link', models.URLField(max_length=100)),
            ],
        ),
    ]
